Error : when validating test16::main
 --> test_resources/templates/test16.yr:(7,4)
 7  ┃ fn main () {
    ╋    ^^^^
    ┃ Error : template specialization for test16::foo {F : fn (ref mut U, i32)-> Z, Z, U} fails with {U=> i32, Z=> i32, F=> (mut ref x : mut i32, y : i32)-> i32}
    ┃  --> test_resources/templates/test16.yr:(9,13)
    ┃  9  ┃     let z = foo!{|ref mut x : i32, y| => { x = 1; x + y }} (ref x);
    ┃     ╋             ^^^
    ┃     ┃ Error : when validating test16::foo!{i32, i32, (mut ref x : mut i32, y : i32)-> i32}::foo
    ┃     ┃  --> test_resources/templates/test16.yr:(3,4)
    ┃     ┃  3  ┃ fn foo {F : fn (ref mut U, i32)-> Z, Z, U} (ref mut a : U)-> Z {
    ┃     ┃     ╋    ^^^
    ┃     ┃     ┃ Error : the call operator is not defined for fn (ref mut i32, i32)-> i32 and {a : mut i32, 23 : i32}
    ┃     ┃     ┃  --> test_resources/templates/test16.yr:(4,7)
    ┃     ┃     ┃  4  ┃     F (a, 23)
    ┃     ┃     ┃     ╋       ^
    ┃     ┃     ┃     ┃ Note : candidate fn (ref mut i32, i32)-> i32 -- (test_resources/templates/test16.yr:(9,18))
    ┃     ┃     ┃     ┃     ┃ Error : cannot pass value of type mut i32 as reference
    ┃     ┃     ┃     ┃     ┃  --> test_resources/templates/test16.yr:(4,8)
    ┃     ┃     ┃     ┃     ┃  4  ┃     F (a, 23)
    ┃     ┃     ┃     ┃     ┃     ╋        ^
    ┃     ┃     ┃     ┃     ┃     ┗━━━━━━━
    ┃     ┃     ┃     ┃     ┗━━━━━┻━
    ┃     ┃     ┃     ┗━━━━━┻━
    ┃     ┃     ┗━━━━━┻━
    ┃     ┗━━━━━┻━
    ┃ Error : the call operator is not defined for {std::io::println {F, T...}, std::io::println, std::io::println {T}} and {z : error, " "s8 : mut [c8], x : mut i32}
    ┃  --> test_resources/templates/test16.yr:(10,13)
    ┃ 10  ┃     println (z, " ", x);
    ┃     ╋             ^
    ┃     ┃ Note : value z is of type error
    ┃     ┃  --> test_resources/templates/test16.yr:(10,14)
    ┃     ┃ 10  ┃     println (z, " ", x);
    ┃     ┃     ╋              ^
    ┃     ┃     ┗━━━━━━━
    ┃     ┗━━━━━┻━
    ┗━━━━━┻━
