Error : when validating test17::main
 --> test_resources/templates/test17.yr:(7,4)
 7  ┃ fn main () {
    ╋    ^^^^
    ┃ Error : undefined template call for test17::foo {F : fn (ref mut U, i32)-> Z, Z, U}(ref mut a : U)-> Z with {(x : i32, y)-> _}
    ┃  --> test_resources/templates/test17.yr:(9,16)
    ┃  9  ┃     let z = foo!{|x : i32, y| => { x + y }} (ref x);
    ┃     ╋                ^
    ┃     ┃ Error : incompatible types fn (ref mut i32, i32)-> i32 and fn (i32, i32)-> i32
    ┃     ┃  --> test_resources/templates/test17.yr:(9,18)
    ┃     ┃  9  ┃     let z = foo!{|x : i32, y| => { x + y }} (ref x);
    ┃     ┃     ╋                  ^
    ┃     ┃     ┃ Note :
    ┃     ┃     ┃  --> test_resources/templates/test17.yr:(3,13)
    ┃     ┃     ┃  3  ┃ fn foo {F : fn (ref mut U, i32)-> Z, Z, U} (ref mut a : U)-> Z {
    ┃     ┃     ┃     ╋             ^^
    ┃     ┃     ┃     ┗━━━━━━━
    ┃     ┃     ┗━━━━━┻━
    ┃     ┗━━━━━┻━
    ┃ Error : the call operator is not defined for {std::io::println {F, T...}, std::io::println, std::io::println {T}} and {z : error, " "s8 : mut [c8], x : mut i32}
    ┃  --> test_resources/templates/test17.yr:(10,13)
    ┃ 10  ┃     println (z, " ", x);
    ┃     ╋             ^
    ┃     ┃ Note : value z is of type error
    ┃     ┃  --> test_resources/templates/test17.yr:(10,14)
    ┃     ┃ 10  ┃     println (z, " ", x);
    ┃     ┃     ╋              ^
    ┃     ┃     ┗━━━━━━━
    ┃     ┗━━━━━┻━
    ┗━━━━━┻━
