Error : when validating test1::main
 --> test_resources/commit_3dc35/test1.yr:(13,4)
13  ┃ fn main () {
    ╋    ^^^^
    ┃ Error : test1::foo called with {1u64} works with multiple candidates
    ┃  --> test_resources/commit_3dc35/test1.yr:(16,9)
    ┃ 16  ┃     foo (1u64);
    ┃     ╋         ^
    ┃     ┃ Note : candidate test1::foo (a : i32)-> void -- (test_resources/commit_3dc35/test1.yr:(6,8))
    ┃     ┃ Note : candidate test1::foo (a : i64)-> void -- (test_resources/commit_3dc35/test1.yr:(9,8))
    ┃     ┗━━━━━━
    ┗━━━━━┻━
