Error : when validating test6::main
 --> test_resources/lit_class/errors/test6.yr:(11,4)
11  ┃ fn main () {
    ╋    ^^^^
    ┃ Error : cannot create a function pointer from the unsafe function a.test6::A::foo (i : *i32)-> void
    ┃  --> test_resources/lit_class/errors/test6.yr:(13,13)
    ┃ 13  ┃     let z = &a.foo;
    ┃     ╋             ^
    ┃     ┗━━━━━━━
    ┃ Error : the call operator is not defined for z : error and {&(f) : mut *i32}
    ┃  --> test_resources/lit_class/errors/test6.yr:(16,7)
    ┃ 16  ┃     z (&f);
    ┃     ╋       ^
    ┃     ┃ Error : defined here
    ┃     ┃  --> test_resources/lit_class/errors/test6.yr:(13,9)
    ┃     ┃ 13  ┃     let z = &a.foo;
    ┃     ┃     ╋         ^
    ┃     ┃     ┃ Note : call operator is not defined for type error -- (test_resources/lit_class/errors/test6.yr:(16,7))
    ┃     ┃     ┗━━━━━━
    ┃     ┗━━━━━┻━
    ┗━━━━━┻━
