Error : when validating test15::main
 --> test_resources/control_flow/test15.yr:(1,4)
 1  ┃ fn main () {
    ╋    ^^^^
    ┃ Error : conditional test is always evaluated to true, branch is always entered
    ┃  --> test_resources/control_flow/test15.yr:(3,15)
    ┃  3  ┃     if (a.len <= 3) { // error, len of /a/ is /cte/
    ┃     ╋               ^^
    ┃     ┗━━━━━━━    
    ┃ Error : conditional test is always evaluated to false, branch is never entered
    ┃  --> test_resources/control_flow/test15.yr:(7,15)
    ┃  7  ┃     if (a.len >= 4) {
    ┃     ╋               ^^
    ┃     ┗━━━━━━━    
    ┗━━━━━┻━ 
