fn main ()
    throws AssertError
{
    let mut i = 9;
    let _a_ = match i {
        12 => { 23 }
        _ => throw copy AssertError ("");
    };

    let _b_ = match i {
        12 => { throw copy AssertError (""); }
        _ => { 23 }
    };
}
