Error : when validating
 --> test_resources/lit_class/ctors/test18.yr:(14,7)
14  ┃ class B over A {
    ╋       ^
    ┃ Error : when validating test18::B::self
    ┃  --> test_resources/lit_class/ctors/test18.yr:(15,9)
    ┃ 15  ┃     pub self ()
    ┃     ╋         ^^^^
    ┃     ┃ Error : the function test18::B::self might throw an exception of type test18::Z, but that is not declared in its prototype
    ┃     ┃  --> test_resources/lit_class/ctors/test18.yr:(15,9)
    ┃     ┃ 15  ┃     pub self ()
    ┃     ┃     ╋         ^^^^
    ┃     ┃     ┃ Note :
    ┃     ┃     ┃  --> test_resources/lit_class/ctors/test18.yr:(16,25)
    ┃     ┃     ┃ 16  ┃         with super (foo ())
    ┃     ┃     ┃     ╋                         ^
    ┃     ┃     ┃     ┗━━━━━━━
    ┃     ┃     ┗━━━━━┻━
    ┃     ┗━━━━━┻━
    ┗━━━━━┻━
