Error : when validating
 --> test_resources/struct/test1.yr:(11,8)
11  ┃ record C {
    ╋        ^
    ┃ Error : record or entity type test1::C has no size due to forward references
    ┃  --> test_resources/struct/test1.yr:(11,8)
    ┃ 11  ┃ record C {
    ┃     ╋        ^
    ┃     ┃ Note : for the field c
    ┃     ┃  --> test_resources/struct/test1.yr:(8,9)
    ┃     ┃  8  ┃     let c : C;
    ┃     ┃     ╋         ^
    ┃     ┃     ┃ Note : within type test1::B
    ┃     ┃     ┃  --> test_resources/struct/test1.yr:(7,8)
    ┃     ┃     ┃  7  ┃ record B {
    ┃     ┃     ┃     ╋        ^
    ┃     ┃     ┃     ┗━━━━━━━
    ┃     ┃     ┗━━━━━┻━
    ┃     ┃ Note : for the field b
    ┃     ┃  --> test_resources/struct/test1.yr:(12,9)
    ┃     ┃ 12  ┃     let b : B;
    ┃     ┃     ╋         ^
    ┃     ┃     ┃ Note : within type test1::C
    ┃     ┃     ┃  --> test_resources/struct/test1.yr:(11,8)
    ┃     ┃     ┃ 11  ┃ record C {
    ┃     ┃     ┃     ╋        ^
    ┃     ┃     ┃     ┗━━━━━━━
    ┃     ┃     ┗━━━━━┻━
    ┃     ┗━━━━━┻━
    ┗━━━━━┻━
Error : when validating
 --> test_resources/struct/test1.yr:(3,8)
 3  ┃ record A {
    ╋        ^
    ┃ Error : record or entity type test1::A has no size due to forward references
    ┃  --> test_resources/struct/test1.yr:(3,8)
    ┃  3  ┃ record A {
    ┃     ╋        ^
    ┃     ┃ Note : for the field a
    ┃     ┃  --> test_resources/struct/test1.yr:(4,9)
    ┃     ┃  4  ┃     let a : A;
    ┃     ┃     ╋         ^
    ┃     ┃     ┃ Note : within type test1::A
    ┃     ┃     ┃  --> test_resources/struct/test1.yr:(3,8)
    ┃     ┃     ┃  3  ┃ record A {
    ┃     ┃     ┃     ╋        ^
    ┃     ┃     ┃     ┗━━━━━━━
    ┃     ┃     ┗━━━━━┻━
    ┃     ┗━━━━━┻━
    ┗━━━━━┻━
