frame : test12::baz (_ : [c8])-> void {
    <unit-value>
}
frame : test12::main ()-> void if try {
    {
        (test12::foo (false))?
    }
} catch {
    let #_catch : mut &(mut core::exception::Exception)
    {
        none
    }
}.hasValue {
    test12::baz ("Yes"s8);
    <unit-value>
} else {
    test12::baz ("No"s8);
    <unit-value>
}
frame : test12::foo (x : bool = true)-> i32 return {
    if !x throw core::exception::AssertError::self(new, ""s8);
    12
}
