frame : test2::main ()-> void {
    #{
        throw core::exception::AssertError::self(new, ""s8)
    #};
    <unit-value>
}
