Error : when validating test3::main
 --> test_resources/scope_guards/test3.yr:(20,4)
20  ┃ fn main ()
    ╋    ^^^^
    ┃ Error : when validating catching pattern with type &(core::exception::Exception)
    ┃  --> test_resources/scope_guards/test3.yr:(24,7)
    ┃ 24  ┃     } catch {
    ┃     ╋       ^^^^^
    ┃     ┃ Error : matcher expression is never evaluated
    ┃     ┃  --> test_resources/scope_guards/test3.yr:(33,11)
    ┃     ┃ 33  ┃         C () => {
    ┃     ┃     ╋           ^
    ┃     ┃     ┗━━━━━━━
    ┃     ┗━━━━━┻━
    ┗━━━━━┻━
